# Change these first
owner: idunwannagotoschool # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Home
    url: https://idunwannagotoschool.com
    icon: https://idunwannagotoschool.com/favicon.ico
  - name: RSS
    url: https://rss.idunwannagotoschool.com
    icon: https://rss.idunwannagotoschool.com/favicon.ico
  - name: Spotify
    url: https://spotify.idunwannagotoschool.com
    icon: https://spotify.idunwannagotoschool.com/favicon.ico
  - name: test
    url: https://thissitedoesnotexist.koj.co/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.nets.hk
  # baseUrl: /your-repo-name
  favicon: https://raw.githubusercontent.com/idunwannagotoschool/upptime/master/assets/stats.png
  logoUrl: https://raw.githubusercontent.com/idunwannagotoschool/upptime/master/assets/stats.png
  theme: night
  name: Uptime
  introTitle: "Did you go to school today?"
  introMessage: This is a simple status page which uses **real-time** data from my [GitHub repository](https://github.com/idunwannagotoschool/uptime) to monitor if the websites are **working hard**. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: idunwannagotoschool
      href: https://idunwannagotoschool.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
