# Change these first
owner: idunwannagotoschool # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Home
    url: https://idunwannagotoschool.com
    icon: https://idunwannagotoschool.com/favicon.ico
  - name: Homepage
    url: https://mojito.eu.org
    icon: https://mojito.eu.org/homepage.ico
  - name: RSS
    url: https://rss.idunwannagotoschool.com
    icon: https://rss.idunwannagotoschool.com/favicon.ico
  - name: Spotify
    url: https://spotify.idunwannagotoschool.com/?gname=Last+day&token=3206cc0f-fd4d-413e-8f91-11b24dcd9886
    icon: https://spotify.idunwannagotoschool.com/favicon.ico
  - name: Filestash
    url: https://file.mojito.eu.org
    icon: https://file.mojito.eu.org/favicon.ico
  - name: InfCloud
    url: https://inf.mojito.eu.org
    icon: https://inf.mojito.eu.org/favicon.ico
  - name: AUYEUNG's
    url: https://auyeung.eu.org
    icon: https://auyeung.eu.org/favicon.ico
  - name: Secret Site 1
    url: $SITE_1
  - name: Secret Site 2
    url: $SITE_2
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.nets.hk
  # baseUrl: /your-repo-name
  favicon: https://raw.githubusercontent.com/idunwannagotoschool/upptime/master/assets/stats.png
  logoUrl: https://raw.githubusercontent.com/idunwannagotoschool/upptime/master/assets/stats.png
  theme: night
  name: Uptime
  introTitle: "Did you go to school today?"
  introMessage: This is a simple status page which uses **real-time** data from my [GitHub repository](https://github.com/idunwannagotoschool/uptime) to monitor if the websites are **working hard**. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: idunwannagotoschool
      href: https://idunwannagotoschool.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
